chore(parser): add parser to release steps
aws-powertools/powertools-lambda-typescript pull request #2382
Opened 2024-04-16 15:55 UTC by am29d

## Description of your changes

This PR adds the necessary configurations so we can release `@aws-lambda-powertools/parser` package as a beta in the next release.

### Related issues, RFCs

**Issue number:** closes #2366 

## Checklist

- [ ] [My changes meet the tenets criteria](https://docs.powertools.aws.dev/lambda/typescript/#tenets)
- [ ] I have performed a *self-review* of my own code
- [ ] I have *commented* my code where necessary, particularly in areas that should be flagged with a TODO, or hard-to-understand areas
- [ ] I have made corresponding changes to the *documentation*
- [ ] My changes generate *no new warnings*
- [ ] I have *added tests* that prove my change is effective and works
- [ ] The PR title follows the [conventional commit semantics](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/.github/semantic.yml#L2)

### Breaking change checklist

***Is it a breaking change?:*** NO

- [ ] I have documented the migration process
- [ ] I have added, implemented necessary warnings (if it can live side by side)

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2024-04-16 15:59 UTC, dreamorosi requested changes

2024-04-16 15:59 UTC, dreamorosi commented on .github/actions/cached-node-modules/action.yml
Please leave the `npm run build -w packages/jmespath` as second & without a `& \`.

We need it to run right after commons & before all others, otherwise there can be race conditions since we are artificially parallelizing all the others.

2024-04-16 16:01 UTC, am29d commented on .github/actions/cached-node-modules/action.yml
Ah that explains the broken builds, I was a bit confused about that.

2024-04-16 16:12 UTC, dreamorosi approved these changes
Thanks for working on this, looking forward to release this as beta!

2024-04-16 16:13 UTC, dreamorosi commented
If you want to wait to merge it, tomorrow morning I can try running the lerna & pack commands locally and we can use this PR to fix any issue.

If instead you have already tested and know it works, merge away!

2024-04-16 16:48 UTC, am29d commented
You are right, let me first have the dry run tomorrow and then I can merge.

2024-04-16 20:37 UTC, dreamorosi requested changes
We need to also set the `"publishConfig"` to `"access": "public"` in the `package.json` file of the utility, or it won't be published to npmjs.com.

2024-04-17 06:23 UTC, dreamorosi commented
I also think we should put back disclaimers on the utility's README and docs page to call out that it's still in beta, that we'd like feedback, and that its API might change.

2024-04-17 08:05 UTC, dreamorosi approved these changes
Thanks for addressing the comments - I manually built the package & tested it in a function and basic features seem to work.

I have a couple questions but we can address them in the coming weeks, nothing blocking imo

2024-04-17 08:45 UTC, merged