fix(parser): links the error cause with ParseError
aws-powertools/powertools-lambda-typescript pull request #2774
Opened 2024-07-14 20:10 UTC by tusharf5

## Summary

fixes #2773

### Changes

> Please provide a summary of what's being changed

The ParseError links the passed error cause with the thrown error. 

> Please add the issue number below, if no issue is present the PR might get blocked and not be reviewed

#2773

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2024-07-14 23:00 UTC, dreamorosi requested changes
Thank you so much for taking the time to open this PR!

I have left a couple of comments that I think we should address before merging it.

2024-07-14 23:00 UTC, dreamorosi commented on packages/parser/tests/unit/envelope.test.ts
Could you please add the lines below at the very top of this file? I just realized this test is actually not being run in the CI:

```ts
/**
 * Test parser envelope
 *
 * @group unit/parser
 */
```

thanks.

2024-07-15 04:50 UTC, tusharf5 commented
@dreamorosi  Made the changes based on the feedback, thanks.

2024-07-15 08:37 UTC, dreamorosi approved these changes
Thank you for addressing the feedback, merging it!

2024-07-15 08:39 UTC, merged