test(tracer): streamline e2e test structure
aws-powertools/powertools-lambda-typescript pull request #3031
Opened 2024-09-06 10:52 UTC by dreamorosi

## Summary

### Changes

> Please provide a summary of what's being changed

This PR simplifies the end to end test structure for the Tracer integration tests by reducing the amount of duplication and overlap between test cases.

The new structure, while still with some room for improvement, tries to address the main code paths & features for each instrumentation method and selectively uses some shared features in each one of them.

In addition to the changes above, I also simplified how values are passed from the test to the AWS Lambda functions ran as part of the tests. Before the change, the values were shared like this:

```mermaid
flowchart TD
    A[constants.ts] -->|imports values| B[test file]
    B -->|deploys w/ env variables| C[lambda function]
    C -->|reads env vars| D[function uses values]
    B -->|asserts that values as expected| D
```

after the change:

```mermaid
flowchart TD
    A[constants.ts] -->|imports values| B[test file]
    A -->|imports values| C[lambda function uses values]
    B -->|asserts that values as expected| C
```

While the change doesn't appear significant in its diagram representation, importing the values directly in both the tests and the function allows us to remove a considerable amount of boilerplate code needed to pass and parse environment variables on both sides.

The PR also improves the X-Ray trace utilities in `packages/testing` to retry loading the trace data when certain subsegments are not present when the trace is first loaded.

> Please add the issue number below, if no issue is present the PR might get blocked and not be reviewed

**Issue number:** closes #3028

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Disclaimer**: We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be successful.

2024-09-06 10:55 UTC, dreamorosi commented
I've run the [integration tests ~10 times](https://github.com/aws-powertools/powertools-lambda-typescript/actions/workflows/run-e2e-tests.yml) over the past few hours and the flakiness on the Tracer tests is greatly reduced, as well as the runtime for these tests.

There have been some transient failures in other areas (Logger & Idempotency) which consistently disappear on the next retry. I'll work on these at some point in the future but for the sake of keeping this PR focused, I'm working only on Tracer.

2024-09-09 12:51 UTC, leandrodamascena requested changes
Hi @dreamorosi! Awesome work refactoring these tests and testing what's important, I mean: handler, standalone function, SDK tracer, HTTP tracer, coldStart, annotation and others.

My only question about the tests in general is the use of `for` and logic inside these loops. I don't know if you can break it down into more small tests to test specific things like "first invocation with coldstart", "second invocation" and so on. You already have the data, so if possible, you should be more specific and reduce the cognitive load to understand the test.

Marking this PR as "Request Changes" to hear from you if we can change anything or if we merge this PR as is.

2024-09-09 14:27 UTC, dreamorosi commented on packages/tracer/tests/e2e/decorator.test.ts
> +      for (let i = 0; i < invocationCount; i++) {
Good point - splitting it into different test cases improves maintainability

2024-09-09 14:50 UTC, dreamorosi commented
Hey @leandrodamascena, thank you for the review & the useful suggestion.

I've broken down the tests and ran them again (green): https://github.com/aws-powertools/powertools-lambda-typescript/actions/runs/10775415657

2024-09-09 14:57 UTC, leandrodamascena approved these changes
APPROVED!

2024-09-09 20:14 UTC, merged